syncfusion/SfQtWebKit

qtbase/src/gui/painting/qpdf.cpp, qtbase/src/gui/painting/qpdf_p.h, qtwebkit/Source/WebCore/page/Frame.cpp, qtwebkit/Source/WebCore/page/Frame.h, qtwebkit/Source/WebCore/page/FrameView.cpp, qtwebkit/Source/WebCore/page/FrameView.h, qtwebkit/Source/WebCore/page/PrintContext.cpp, qtwebkit/Source/WebCore/page/PrintContext.h, qtwebkit/Source/WebKit/qt/Api/qwebelement.h, qtwebkit/Source/WebKit/qt/WebCoreSupport/QtPrintContext.cpp, qtwebkit/Source/WebKit/qt/WebCoreSupport/QtPrintContext.h, qtwebkit/Source/WebKit/qt/WidgetApi/qwebframe.cpp, qtwebkit/Source/WebKit/qt/WidgetApi/qwebframe.h, qtwebkit/Source/WebKit/qt/WidgetApi/qwebframe_p.h
=> Qt webkit fixes

qtwebkit/Source/WebCore/platform/network/qt/QNetworkReplyHandler.cpp
Added HTTP POST request support.
=> Added HTTP POST request support

qtbase/src/gui/painting/qpdf.cpp, qtbase/src/gui/painting/qpdf_p.h
Improved performance of Webkit HTML to PDF converter.
=> Improved performance of Webkit HTML to PDF converter.

qtbase/src/gui/painting/qpdf.cpp, qtbase/src/gui/painting/qpdf_p.h, qtwebkit/Source/WebCore/page/PrintContext.cpp, qtwebkit/Source/WebCore/page/PrintContext.h, qtwebkit/Source/WebKit/qt/WebCoreSupport/QtPrintContext.cpp, qtwebkit/Source/WebKit/qt/WebCoreSupport/QtPrintContext.h, qtwebkit/Source/WebKit/qt/WidgetApi/qwebframe.cpp, qtwebkit/Source/WebKit/qt/WidgetApi/qwebframe.h
Added support for partial webpage conversion in HTML to PDF
=> Added support for partial webpage conversion

qtwebkit/Source/WebCore/page/FrameView.h, qtwebkit/Source/WebCore/page/PrintContext.h, qtwebkit/Source/WebCore/rendering/RenderTable.cpp, qtwebkit/Source/WebCore/rendering/RenderTableSection.cpp, qtwebkit/Source/WebCore/rendering/RenderTableSection.h, qtwebkit/Source/WebCore/rendering/RenderView.cpp, qtwebkit/Source/WebCore/rendering/RenderView.h, qtwebkit/Source/WebKit/qt/WebCoreSupport/QWebFrameAdapter.cpp, qtwebkit/Source/WebKit/qt/WebCoreSupport/QWebFrameAdapter.h, qtwebkit/Source/WebKit/qt/WebCoreSupport/QtPrintContext.cpp, qtwebkit/Source/WebKit/qt/WidgetApi/qwebpage.cpp, qtwebkit/Source/WebKit/qt/WidgetApi/qwebpage.h
Added support for repeat table header and footer on every page break.
=> Added support for repeat table header and footer on every page break.

qtwebkit/Source/WebCore/page/Frame.h, qtwebkit/Source/WebCore/rendering/RenderTableSection.cpp
Fixed the table row preservation issue
=> Fixed the table row preservation issue

qtbase/src/gui/painting/qpainter.cpp, qtwebkit/Source/WebCore/platform/graphics/Image.cpp
Fixed the pattern rendering issue in PDF
=> Fixed the pattern rendering issue in PDF

qtsvg/src/svg/qsvggenerator.cpp
Fixed the memory allocation exception while converting large HTML to
SVG​​​​​​
=> Fixed the memory allocation exception while converting large HTML to SVG​​​​​​

qtwebkit/Source/WebCore/loader/DocumentLoader.cpp
Fixed the hanging issue in MHTML to PDF conversion
=> Fixed the hanging issue in MHTML to PDF conversion

qtsvg/src/svg/qsvggenerator.cpp
Fixed the file size issue in HTML to SVG conversion
=> Fixed the file size issue in HTML to SVG conversion

qtsvg/src/svg/qsvggenerator.cpp
Fixed the view box issue in HTML to SVG conversion
=> Fixed the view box issue in HTML to SVG conversion

qtbase/src/network/access/qnetworkaccessfilebackend.cpp
Fixed the image loading issue in WebKit HTML converter
=> Fixed the image loading issue in WebKit HTML converter

qtbase/src/plugins/platforms/windows/qwindowscontext.cpp
Suppressed the OLE initialization failed warning
=> Suppressed the OLE initialization failed warning

qtbase/src/gui/text/qfontsubset.cpp
Fixed the corruption issue while converting particular HTML to PDF.
=> Fixed the corruption issue while converting particular HTML to PDF.

qtwebkit/Source/WebCore/page/PrintContext.cpp
Fixed the issue with partial HTML to PDF conversion
=> Fixed the issue with partial HTML to PDF conversion

qtbase/src/gui/image/qjpeghandler.cpp
Fixed the issue with decoding of JPEG image with invalid headers
=> Fixed the issue with decoding of JPEG image with invalid headers

qtbase/src/gui/text/qrawfont.cpp, qtbase/src/gui/text/qrawfont_p.h
Fixed the issue with incorrect spacing between the letters.
=> Fixed the issue with incorrect spacing between the letters.

qtbase/src/gui/painting/qpdf.cpp
Fixed the issue with bold text rendering in PDF
=> Fixed the issue with bold text rendering in PDF

qtbase/src/gui/text/qrawfont.cpp, qtbase/src/gui/text/qrawfont_p.h
Improved the performance of WebKit HTML converter
=> Improved the performance of WebKit HTML converter

qtwebkit/Source/WebCore/rendering/RenderTable.cpp
Fixed the issue with HTML table header repeated twice on pagination
=> Fixed the issue with HTML table header repeated twice on pagination

qtbase/src/gui/painting/qpdf.cpp
Fixed the issue with factor calculation for form fields.
=> Fixed the issue with factor calculation for form fields.

qtbase/src/network/access/qhttpnetworkconnection.cpp
Fixed the issue with windows authentication for HTML conversion
=> Fixed the issue with windows authentication for HTML conversion

qtwebkit/Source/WebCore/css/CSSCalculationValue.cpp, qtwebkit/Source/WebKit/qt/WebCoreSupport/QtPrintContext.cpp
Fixed the issue with access violation exception in HTML to PDF conversion
=> Fixed the issue with access violation exception in HTML to PDF conversion

qtwebkit/Source/WebCore/rendering/RenderTableCell.cpp
Fixed the row span border preservation issue.
=> Fixed the row span border preservation issue.
